In [1]:
import numpy as np
import sklearn
import xgboost as xgb

from sklearn.model_selection import GridSearchCV 
from data_generation import get_data

In [90]:
#np.random.seed(seed=123)
N = 10000
y_data, d_data, x_data = get_data(N)

XGBRegressor(objective='reg:logistic') and XGBClassifier(objective='binary:logistic') are the same algorithms under the hood. 

In [99]:
xgb_model_m = xgb.XGBRegressor(objective='reg:logistic', n_estimators=25, max_depth=3, subsample=0.7)
xgb_model_m.fit(X=x_data, y=d_data)
xgb_model_m.predict(x_data[-15:])

array([0.86036175, 0.80998915, 0.63795793, 0.197225  , 0.6864021 ,
       0.68612653, 0.25093997, 0.88650364, 0.72481173, 0.66614354,
       0.96310997, 0.25210655, 0.21577947, 0.5704212 , 0.2631983 ],
      dtype=float32)

In [100]:
#xgb_model_m = xgb.XGBRegressor(objective='reg:logistic', n_estimators=25, max_depth=3, seed=3, subsample=0.7)
xgb_model_m.fit(X=x_data, y=d_data)
xgb_model_m.predict(x_data[-15:])

array([0.86036175, 0.80998915, 0.63795793, 0.197225  , 0.6864021 ,
       0.68612653, 0.25093997, 0.88650364, 0.72481173, 0.66614354,
       0.96310997, 0.25210655, 0.21577947, 0.5704212 , 0.2631983 ],
      dtype=float32)

In [101]:
xgb_model_m = xgb.XGBClassifier(objective='binary:logistic', n_estimators=25, max_depth=3, seed=0, subsample=0.7)
xgb_model_m.fit(X=x_data, y=d_data)
xgb_model_m.predict_proba(x_data[-15:])[:,1]

array([0.86036175, 0.80998915, 0.63795793, 0.197225  , 0.6864021 ,
       0.68612653, 0.25093997, 0.88650364, 0.72481173, 0.66614354,
       0.96310997, 0.25210655, 0.21577947, 0.5704212 , 0.2631983 ],
      dtype=float32)

In [41]:
np.random.uniform(1,2)

1.430021543509957