In [1]:
import numpy as np

In [13]:
np.random.seed(42)

In [22]:
rng = np.random.default_rng(42)

In [23]:
rng.uniform(size=2)

array([0.77395605, 0.43887844])

In [14]:
np.random.uniform(size=2)

array([0.37454012, 0.95071431])

In [44]:
import numpy as np

# Using np.random.seed()
np.random.seed(42)
print(np.random.rand(3))  # [0.37454012 0.95071431 0.73199394]

# Using np.random.default_rng()
rng = np.random.default_rng(42)
print(rng.random(3))

[0.37454012 0.95071431 0.73199394]
[0.77395605 0.43887844 0.85859792]
