In [1]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
from scipy.stats import norm
from data_generation import m_0, g_0, get_data

In [40]:
np.random.seed(123)
N = 2000
y_data, d_data, x_data = get_data(N)

In [5]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Input

In [6]:
def get_model_g():
    np.random.seed(42)
    tf.random.set_seed(42)
    model = Sequential()
    model.add(Input(shape=(3,)))
    model.add(Dense(8, activation='relu'))
    model.add(Dropout(0.2))
    model.add(Dense(1))
    model.compile(loss='mean_squared_error', optimizer='adam')
    return model

In [17]:
model_g0 = get_model_g()
model_g0.fit(x_data[d_data==0], y_data[d_data==0], epochs=50, batch_size=8, validation_split=0.2)

Epoch 1/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 1.4101 - val_loss: 1.1293
Epoch 2/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0729 - val_loss: 1.0095
Epoch 3/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8490 - val_loss: 0.9244
Epoch 4/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.8224 - val_loss: 0.8627
Epoch 5/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7531 - val_loss: 0.8177
Epoch 6/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.8390 - val_loss: 0.7798
Epoch 7/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6790 - val_loss: 0.7483
Epoch 8/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6150 - val_loss: 0.7184
Epoch 9/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6202 - val_loss: 0.6828
Epoch 10/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6752 - val_loss: 0.6406
Epoch 11/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5506 - val_loss: 0.5975
Epoch 12/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5193 - val_lo

In [21]:
model_g1 = get_model_g()
model_g1.fit(x_data[d_data==1], y_data[d_data==1], epochs=50, batch_size=8, validation_split=0.2)

Epoch 1/50
116/116 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1.5151 - val_loss: 1.0046
Epoch 2/50
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0642 - val_loss: 0.8181
Epoch 3/50
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9292 - val_loss: 0.7266
Epoch 4/50
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.8594 - val_loss: 0.6631
Epoch 5/50
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7754 - val_loss: 0.6145
Epoch 6/50
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6989 - val_loss: 0.5814
Epoch 7/50
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7635 - val_loss: 0.5562
Epoch 8/50
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6445 - val_loss: 0.5318
Epoch 9/50
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6392 - val_loss: 0.5119
Epoch 10/50
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6159 - val_loss: 0.5011
Epoch 11/50
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5779 - val_loss: 0.4955
Epoch 12/50
116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [7]:
def get_model_m():
    np.random.seed(42)
    tf.random.set_seed(42)
    model = Sequential()
    model.add(Input(shape=(3,)))
    model.add(Dense(8, activation='relu'))
    model.add(Dropout(0.2))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam')
    return model

In [24]:
model_m = get_model_m()
model_m.fit(x_data, d_data, epochs=50, batch_size=8, validation_split=0.2)

Epoch 1/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.8024 - val_loss: 0.6657
Epoch 2/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6667 - val_loss: 0.5986
Epoch 3/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6078 - val_loss: 0.5597
Epoch 4/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.5816 - val_loss: 0.5320
Epoch 5/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5633 - val_loss: 0.5229
Epoch 6/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5487 - val_loss: 0.5170
Epoch 7/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5397 - val_loss: 0.5134
Epoch 8/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5615 - val_loss: 0.5139
Epoch 9/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.5374 - val_loss: 0.5108
Epoch 10/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5439 - val_loss: 0.5112
Epoch 11/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.5345 - val_loss: 0.5102
Epoch 12/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [25]:
model_m.predict(x_data)[-15:].flatten()

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


array([0.5015063 , 0.23748566, 0.23498721, 0.57617116, 0.95479804,
       0.8149565 , 0.18577808, 0.0717039 , 0.49484137, 0.88676393,
       0.19101728, 0.67287433, 0.19483322, 0.36960047, 0.97165954],
      dtype=float32)

In [26]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(x_data, d_data)
logreg.predict_proba(x_data)[-15:, 1]

array([0.52299913, 0.23061248, 0.22093542, 0.61482272, 0.9696206 ,
       0.84365511, 0.17402417, 0.05674818, 0.51037002, 0.89810764,
       0.19067747, 0.64418453, 0.17727966, 0.37566057, 0.98275592])

In [27]:
m_0(x_data)[-15:]

array([0.53036433, 0.2380795 , 0.21096953, 0.60356209, 0.96932331,
       0.83427489, 0.18103707, 0.05851277, 0.52812732, 0.91113921,
       0.23055662, 0.67168921, 0.16800972, 0.36636657, 0.98300499])

In [28]:
import xgboost as xgb

model_xgb = xgb.XGBClassifier(objective='binary:logistic', max_depth=3, subsample=0.8, learning_rate=0.06, reg_lambda=3)
model_xgb.fit(x_data, d_data)
model_xgb.predict_proba(x_data)[-15:, 1]

array([0.3750922 , 0.19057377, 0.34025028, 0.64574885, 0.9219643 ,
       0.8824051 , 0.2091873 , 0.08840653, 0.45933792, 0.885281  ,
       0.2846234 , 0.48567292, 0.20776446, 0.29364178, 0.9385198 ],
      dtype=float32)

In [36]:
def dml_ate(y_data, d_data, x_data, get_model_g, get_model_m, epochs=50, batch_size=8,
            K=5, classical=True, inference=True, alpha=0.05):
    # Generate random partition of data for cross-fitting
    N = len(y_data)
    skf = StratifiedKFold(n_splits=K, shuffle=True, random_state=42)

    # Compute respective ML estimators and thereupon auxiliary estimators
    theta_0_check_list = []
    if classical:
        reg_check_list, ipw_check_list = [], []
    if inference:
        scores_list = []
    
    for (train_indices, eval_indices) in skf.split(X=x_data, y=d_data):
        y_train, d_train, x_train = y_data[train_indices], d_data[train_indices], x_data[train_indices]
        y_eval, d_eval, x_eval = y_data[eval_indices], d_data[eval_indices], x_data[eval_indices]

        # Estimate outcome regression functions g_0(d)
        g_0_hat = []
        for d in [0, 1]:
            model_g = get_model_g()
            model_g.fit(x_train[d_train==d], y_train[d_train==d], epochs=epochs, batch_size=batch_size, verbose=0)
            g_0_hat.append(model_g.predict(x_eval).flatten())

        # Estimate propensity score m_0
        model_m = get_model_m()
        model_m.fit(x_train, d_train, epochs=epochs, batch_size=batch_size, verbose=0)
        m_0_hat = model_m.predict(x_eval).flatten()
            
        # Compute auxiliary estimator
        scores = g_0_hat[1] - g_0_hat[0] + d_eval*(y_eval-g_0_hat[1])/m_0_hat - (1-d_eval)*(y_eval-g_0_hat[0])/(1-m_0_hat)
        theta_0_check_list.append(np.mean(scores))

        # For variance estimation
        if inference:
            scores_list.append(scores)

        # For regression & IPW estimators
        if classical:
            reg_check_list.append(np.mean(g_0_hat[1] - g_0_hat[0])) 
            ipw_check_list.append(np.mean(d_eval*y_eval/m_0_hat - (1-d_eval)*y_eval/(1-m_0_hat)))     

    # Compute final estimator
    theta_0_hat = np.mean(theta_0_check_list)
    if classical:
        reg_hat, ipw_hat = np.mean(reg_check_list), np.mean(ipw_check_list)

    # Inference: estimate variance and construct confidence interval
    if inference:
        sigma_hat = np.sqrt(np.mean((np.array(scores_list)-theta_0_hat)**2))
        quantile = norm.ppf(1-alpha/2)
        CI = np.array([theta_0_hat-quantile*sigma_hat/np.sqrt(N), theta_0_hat+quantile*sigma_hat/np.sqrt(N)])

    # Return results
    if classical:
        if inference:
            return np.array([theta_0_hat, reg_hat, ipw_hat]), sigma_hat, CI
        else:
            return np.array([theta_0_hat, reg_hat, ipw_hat])
    else:
        if inference:
            return theta_0_hat, sigma_hat, CI
        else:
            return theta_0_hat

In [41]:
%%time
ate_estimates, sigma_hat, CI = dml_ate(y_data, d_data, x_data, get_model_g, get_model_m, K=2)

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
CPU times: total: 1min 10s
Wall time: 49 s


In [42]:
ate_estimates

array([1.01587012, 1.09154916, 1.05139971])

In [43]:
CI

array([0.93775371, 1.09398653])

In [ ]:
results_dict = {}

for N, xgb_params_dict in xgb_params_dict_dict.items():
    model_g0, model_g1 = xgb.XGBRegressor(objective='reg:squarederror'), xgb.XGBRegressor(objective='reg:squarederror')
    model_g0.set_params(**xgb_params_dict['g0'])
    model_g1.set_params(**xgb_params_dict['g1'])
    model_g = [model_g0, model_g1]
    model_m = xgb.XGBClassifier(objective='binary:logistic')
    model_m.set_params(**xgb_params_dict['m'])
    results_dict[N] = mc_simulation(N, model_g, model_m)
    print(f'MC simulation done for N={N}')

with open('results_dict.pkl', 'wb') as pickle_file:
    pickle.dump(results_dict, pickle_file)