In [1]:
import numpy as np
from sklearn.svm import SVR, SVC, LinearSVR, LinearSVC
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.calibration import CalibratedClassifierCV
from data_generation import get_data, g_0, m_0
from dml_algorithm import dml_ate

In [2]:
rng = np.random.default_rng(seed=123)

In [3]:
N = 250
y_data, d_data, x_data = get_data(N, rng)
y_train, y_test, d_train, d_test, x_train, x_test = train_test_split(y_data, d_data, x_data, test_size=0.2, random_state=42)

In [4]:
model_g0, model_g1 = LinearSVR(dual='auto', max_iter=2500), LinearSVR(dual='auto', max_iter=2500)
model_m = CalibratedClassifierCV(estimator=LinearSVC(dual='auto', max_iter=2500)) #, n_jobs=-1
model_m_nonlinear = SVC(probability=True, random_state=42)

In [52]:
N = 250
y_data, d_data, x_data = get_data(N, rng)
y_train, y_test, d_train, d_test, x_train, x_test = train_test_split(y_data, d_data, x_data, test_size=0.2, random_state=42)
model_m = CalibratedClassifierCV(estimator=LinearSVC(dual='auto', max_iter=2500))
model_m_2 = CalibratedClassifierCV(estimator=LinearSVC(dual='auto', max_iter=2500), method='isotonic')

In [53]:
%%time
model_m.fit(x_train, d_train)
print(model_m.predict_proba(x_test)[:20,1])
model_m_2.fit(x_train, d_train)
print(model_m_2.predict_proba(x_test)[:20,1])
print(m_0(x_test[:20]))

[0.75782366 0.1081392  0.4380588  0.13226565 0.22477492 0.32252746
 0.52142833 0.55220563 0.3364116  0.61823012 0.76432348 0.29846205
 0.46542094 0.15033277 0.65025305 0.4393908  0.85164284 0.57002081
 0.63447986 0.04004093]
[0.93333333 0.         0.4512605  0.         0.09203475 0.30238095
 0.4512605  0.4912605  0.33952381 0.67239993 0.93333333 0.27507003
 0.4912605  0.05714286 0.72466527 0.4512605  0.96012949 0.54226408
 0.62380952 0.        ]
[0.8485524  0.09058125 0.30348166 0.02835181 0.13868599 0.39836533
 0.46815584 0.49492956 0.23402002 0.82336364 0.70270092 0.35112246
 0.48414538 0.03198229 0.78706381 0.32661086 0.83445733 0.65141855
 0.6412689  0.00732812]
CPU times: total: 109 ms
Wall time: 115 ms


In [5]:
%%time
model_m_nonlinear.fit(x_train, d_train)
print(model_m_nonlinear.predict_proba(x_test)[:20,1])

[0.44371969 0.67003451 0.3927008  0.62105408 0.25309031 0.22098014
 0.42097072 0.5480654  0.23256244 0.11458508 0.42682796 0.42137584
 0.14298561 0.24871073 0.16245899 0.51344718 0.42198521 0.16191044
 0.1420196  0.53662077]
CPU times: total: 31.2 ms
Wall time: 25.7 ms


In [6]:
%%time
model_m.fit(x_train, d_train)
print(model_m.predict_proba(x_test)[:20,1])
print(m_0(x_test[:20]))

[0.50008592 0.49906333 0.4489987  0.47957785 0.24452864 0.18567368
 0.34367941 0.39485999 0.3320541  0.17202806 0.23358895 0.39394827
 0.27414551 0.38721704 0.22964554 0.68243942 0.2004714  0.28398448
 0.13241459 0.7445053 ]
[0.46757368 0.68835753 0.51556744 0.45580508 0.34717051 0.22212825
 0.61745043 0.53851286 0.54897398 0.21779908 0.36124516 0.27468535
 0.29395314 0.36922943 0.18776022 0.73825664 0.19868991 0.2104203
 0.06405023 0.77528901]
CPU times: total: 78.1 ms
Wall time: 59.6 ms


In [25]:
%%time
model_g0.fit(x_train[d_train==0], y_train[d_train==0])
print(model_g0.predict(x_test[:20]))
print(g_0(0, x_test[:20]))

[11.4632455   5.30767494  3.35901166  6.40824449  5.46382513  3.40826872
  7.42189094  6.91662485  8.43741067  4.88340824  3.86547717  3.4284026
  5.39286796  7.38124728  6.09363294  6.78061771 11.3155003   4.42899936
  5.14482901  6.03170065]
[11.10481305  4.81084654  3.49232755  7.68548576  5.37828441  4.39214381
  6.87728761  6.59457888  7.76416267  4.57344038  3.44898456  2.45140035
  4.70245763  7.06843659  4.86556282  5.81951578 10.55989342  4.63861388
  4.80569948  7.77599696]
CPU times: total: 0 ns
Wall time: 4.99 ms


In [26]:
%%time
model_g1.fit(x_train[d_train==1], y_train[d_train==1])
print(model_g1.predict(x_test[:20]))
print(g_0(1, x_test[:20]))

[11.49032373  6.71187503  3.90991898  5.02139657  4.89251377  4.6772443
  9.05294072  3.85371319  7.90499873  4.31640967  4.86871415  5.05437074
  7.0288738   6.87693955  5.68459337  7.11061007  9.66761433  3.79062485
  4.11061796  8.58651597]
[12.12457538  7.6064959   5.14624058  6.14682521  5.44233397  4.80327703
  9.12791178  4.72869834  7.67342315  3.76316409  5.19723771  3.38574428
  6.52481393  6.87520649  6.42372262  6.52067982 10.32296312  4.56048883
  3.78389008  9.39637862]
CPU times: total: 0 ns
Wall time: 7.9 ms


In [ ]:
C, max_iter

In [ ]:
param_grid = {
    'C': [0.1, 1, 10, 100]
}

In [255]:
%%time
N = 16000
y_data, d_data, x_data = get_data(N, rng)
model_g0, model_g1 = LinearSVR(C=5, dual='auto', max_iter=5000, random_state=42), LinearSVR(C=5, dual='auto', max_iter=5000, random_state=42)
model_g = [model_g0, model_g1]
model_m = CalibratedClassifierCV(estimator=LinearSVC(C=5, dual='auto', max_iter=5000, random_state=42)) #, n_jobs=-1
dml_ate(y_data, d_data, x_data, model_g, model_m, K=5, classical=True, inference=True, alpha=0.05)

CPU times: total: 3.02 s
Wall time: 3 s


(array([0.51908536, 0.55552273, 0.45258778]),
 5.451014995427961,
 array([0.43462256, 0.60354816]))

In [46]:
%%time
model_g0, model_g1 = LinearSVR(dual='auto', max_iter=2500, random_state=42), LinearSVR(dual='auto', max_iter=2500, random_state=42)
model_g = [model_g0, model_g1]
model_m = SVC(probability=True, random_state=42)
dml_ate(y_data, d_data, x_data, model_g, model_m, K=5, classical=True, inference=True, alpha=0.05)

CPU times: total: 984 ms
Wall time: 986 ms


(array([0.5423967 , 0.64183653, 0.10269771]),
 4.224612415082437,
 array([0.28055733, 0.80423608]))

In [193]:
def svm_cv(y_data, d_data, x_data, cv=5):
    model_g = LinearSVR(dual='auto', max_iter=5000, random_state=42)
    #model_m = CalibratedClassifierCV(estimator=LinearSVC(dual='auto', max_iter=5000, random_state=42))
    model_m = SVC(kernel='linear', probability=True, random_state=42)
    
    param_grid = {
        'C': [0.1, 1, 3, 10, 5]
    }

    grid_search_g = GridSearchCV(estimator=model_g, param_grid=param_grid, cv=cv, n_jobs=-1,
                                 scoring='neg_mean_squared_error')
    grid_search_m = GridSearchCV(estimator=model_m, param_grid=param_grid, cv=cv, n_jobs=-1,
                                 scoring='neg_brier_score')

    svm_params_dict = {}
    for d in [0, 1]:
        grid_search_g.fit(X=x_data[d_data == d], y=y_data[d_data == d])
        svm_params_dict[f'g{d}'] = grid_search_g.best_params_
    grid_search_m.fit(X=x_data, y=d_data)
    svm_params_dict['m'] = grid_search_m.best_params_

    return svm_params_dict

In [198]:
for N in [250, 500, 1000]:#, 2000, 4000, 8000, 16000]:
    y_data, d_data, x_data = get_data(N, rng)
    svm_params_dict = svm_cv(y_data, d_data, x_data)
    print(svm_params_dict)

{'g0': {'C': 10}, 'g1': {'C': 5}, 'm': {'C': 10}}
{'g0': {'C': 5}, 'g1': {'C': 3}, 'm': {'C': 10}}


C:\Users\henry\MA_CausalML\dml\Lib\site-packages\sklearn\svm\_base.py:1237: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


{'g0': {'C': 10}, 'g1': {'C': 10}, 'm': {'C': 1}}


In [ ]:
choose C=5!